applications/registro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='registro_app'

urlpatterns = [
    path('listar-docente/',views.DocenteListViewAll.as_view(), name='listar-docente'),
    path('listar-nodocente/',views.NoDocenteListViewAll.as_view(), name='listar-nodocente'),
    path('listar-por-materia/<short_name>/',views.DocenteListViewPorAsignatura.as_view(), name='listar-por-materia'),
    path('detalle-docente/<pk>/',views.DocenteDetailView.as_view(), name='detalle-docente'),
    path('detalle-nodocente/<pk>/',views.NoDocenteDetailView.as_view(), name='detalle-nodocente'),
    path('listar-por-oficina/<short_name>/',views.NoDocenteListViewPorOficina.as_view(), name='listar-por-oficina'),
    path('buscar-por-apellido/',views.DocenteListViewBuscar.as_view(), name='buscar-por-apellido'),
    path("buscar-nodocente-por-apellido/",views.NoDocenteListViewBuscar.as_view(), name="buscar-nodocente"),
    path("exito/",views.SuccessView.as_view(), name="exito"),
    path("alta-docente/",views.DocenteCreateView.as_view(), name="alta-docente"),
    path('alta-nodocente/',views.NoDocenteCreateView.as_view(), name='alta-nodocente'),
    path('update-docente/<pk>',views.DocenteUpdateView.as_view(), name='update-docente'),
    path('update-nodocente/<pk>', views.NoDocenteUpdateView.as_view(), name='update-nodocente'),
    path('delete-docente/<pk>', views.DocenteDeleteView.as_view(), name='delete-docente'),
    path('delete-nodocente/<pk>',views.NoDocenteDeleteView.as_view(), name='delete-nodocente'),
    path('listar-materia/', views.MateriaListViewAll.as_view(), name='listar-materia'),
    path('listar-oficina/', views.OficinaListViewAll.as_view(), name='listar-oficina'),
    path('', views.VistaPrincipal.as_view(), name='index'),
    path('detalle-materia/<pk>', views.MateriaDetailView.as_view(), name='detalle-materia'),
    path('buscar-materia/', views.MateriaListViewBuscar.as_view(), name='buscar-materia'),
    path('alta-materia/', views.MateriaCreateView.as_view(), name='alta-materia'),
    path('update-materia/<pk>', views.MateriaUpdateView.as_view(), name='update-materia'),
    path('delete-materia/<pk>', views.MateriaDeleteView.as_view(), name='delete-materia'),
    path('detalle-oficina/<pk>', views.OficinaDetailView.as_view(), name='detalle-oficina'),
    path('buscar-oficina/', views.OficinaListViewBuscar.as_view(), name='buscar-oficina'),
    path('alta-oficina/', views.OficinaCreateView.as_view(), name='alta-oficina'),
    path('update-oficina/<pk>', views.OficinaUpdateView.as_view(), name='update-oficina'),
    path('delete-oficina/<pk>', views.OficinaDeleteView.as_view(), name='delete-oficina'),
    
]

instituto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('applications.registro.urls')),
    ]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

applications/registro/models.py
from django.db import models

# Create your models here.
class Oficina(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre corto', max_length=50)

    class Meta:
        verbose_name='Oficina'
        verbose_name_plural='Oficinas del Instituto'
        ordering=['name']
    
    def __str__(self):
        return str(self.name)


class NoDocente(models.Model):

    first_name = models.CharField('Nombre', max_length=50)
    last_name = models.CharField('Apellido', max_length=50)
    age= models.IntegerField("Edad")
    oficina = models.ForeignKey(Oficina, on_delete=models.CASCADE)
    avatar = models.ImageField('Imagen', upload_to= 'registro', height_field=None, width_field=None, max_length=None, blank=True)

    

    class Meta:
        """Meta definition for NoDocente."""

        verbose_name = 'No Docente'
        verbose_name_plural = 'No Docentes'

    def __str__(self):
        return self.last_name + ', ' + self.first_name
        

class Materia(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre corto', max_length=50)
    

    class Meta:
        """Meta definition for Materia."""

        verbose_name = 'Materia'
        verbose_name_plural = 'Materias'

    def __str__(self):
        return str(self.name)



class Docente(models.Model):

    first_name = models.CharField('Nombre', max_length=50)
    last_name = models.CharField('Apellido', max_length=50)
    age=models.IntegerField("Edad")
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    avatar = models.ImageField('Imagen', upload_to= 'registro', height_field=None, width_field=None, max_length=None, blank=True)


    class Meta:
        """Meta definition for Docente."""

        verbose_name = 'Docente'
        verbose_name_plural = 'Docentes'

    def __str__(self):
        return self.last_name + ', ' + self.first_name

applications/registro/forms.py
from django import forms
from .models import Docente,NoDocente,Materia,Oficina

class DocenteForm(forms.ModelForm):

    class Meta:
        """Meta definition for Docenteform."""
        model = Docente
        fields = (
        'last_name',
        'first_name',
        'age',
        'materia',
        'avatar',
        )

class NoDocenteForm(forms.ModelForm):

    class Meta:
        """Meta definition for Docenteform."""
        model = NoDocente
        fields = (
        'last_name',
        'first_name',
        'age',
        'oficina',
        'avatar',
        )

class MateriaForm(forms.ModelForm):

    class Meta:
        """Meta definition for Materiaform."""

        model = Materia
        fields = (
            'name',
            'short_name',
            )

class OficinaForm(forms.ModelForm):

    class Meta:
        """Meta definition for Materiaform."""

        model = Oficina
        fields = (
            'name',
            'short_name',
            )   

applications/registro/views.py
from django.shortcuts import render
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    TemplateView,
    UpdateView,
    DeleteView,
)

from django.urls import reverse_lazy
from .models import Docente,NoDocente,Materia,Oficina
from .forms import DocenteForm,NoDocenteForm,MateriaForm,OficinaForm


# Create your views here.
class DocenteListViewAll(ListView):
    model = Docente
    template_name = "registro/list_all_docente.html"
    ordering = 'last_name'
    context_object_name = 'lista_docente'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = Docente.objects.filter(
            last_name__icontains = palabra_clave
        )
        return lista

class MateriaListViewAll(ListView):
    model = Materia
    template_name = "registro/list_all_materia.html"
    ordering = 'name'
    context_object_name = 'lista'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = Materia.objects.filter(
            name__icontains = palabra_clave
        )
        return lista

class OficinaListViewAll(ListView):
    model = Oficina
    template_name = "registro/list_all_oficina.html"
    ordering = 'name'
    context_object_name = 'lista'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = Oficina.objects.filter(
            name__icontains = palabra_clave
        )
        return lista


class NoDocenteListViewAll(ListView):
    model = NoDocente
    template_name = "registro/list_all_nodocente.html"
    ordering= 'last_name'
    context_object_name = 'lista_nodocente'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = NoDocente.objects.filter(
            last_name__icontains = palabra_clave
        )
        return lista

class DocenteListViewPorAsignatura(ListView):
    model = Docente
    template_name = "registro/listar_por_materia.html"
    context_object_name = 'lista'

    def get_queryset(self):
        asignatura = self.kwargs['short_name']
        lista = Docente.objects.filter(
            materia__short_name= asignatura
        )
        return lista

class NoDocenteListViewPorOficina(ListView):
    model = Docente
    template_name = "registro/listar_por_oficina.html"
    context_object_name = 'lista'

    def get_queryset(self):
        oficina = self.kwargs['short_name']
        lista = NoDocente.objects.filter(
            oficina__short_name= oficina
        )
        return lista

class DocenteDetailView(DetailView):
    model = Docente
    template_name = "registro/detalle_docente.html"
    context_object_name = 'detalle_docente'


class NoDocenteDetailView(DetailView):
    model = NoDocente
    template_name = "registro/detalle_nodocente.html"
    context_object_name = 'detalle_nodocente'


class MateriaDetailView(DetailView):
    model = Materia
    template_name = "registro/detalle_materia.html"
    context_object_name = 'detalle_materia'

class OficinaDetailView(DetailView):
    model = Oficina
    template_name = "registro/detalle_oficina.html"
    context_object_name = 'detalle_oficina'


class DocenteListViewBuscar(ListView):
    model = Docente
    template_name = "registro/buscar_docente.html"
    context_object_name = 'lista'

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = Docente.objects.filter(
            last_name = palabra_clave
        )
        return lista

class MateriaListViewBuscar(ListView):
    model = Materia
    template_name = "registro/buscar_materia.html"
    context_object_name = 'lista'

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = Materia.objects.filter(
            name = palabra_clave
        )
        return lista
 
class OficinaListViewBuscar(ListView):
    model = Materia
    template_name = "registro/buscar_oficina.html"
    context_object_name = 'lista'

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = Oficina.objects.filter(
            name = palabra_clave
        )
        return lista

class NoDocenteListViewBuscar(ListView):
    model = NoDocente
    template_name = "registro/buscar_nodocente.html"
    context_object_name = 'lista'

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword','')
        lista = NoDocente.objects.filter(
            last_name = palabra_clave
        )
        return lista



class SuccessView(TemplateView):
    template_name = "registro/exito.html"

class DocenteCreateView(CreateView):
    model = Docente
    template_name = "registro/alta_docente.html"
    form_class = DocenteForm
    success_url = reverse_lazy('registro_app:listar-docente')


class NoDocenteCreateView(CreateView):
    model = NoDocente
    template_name = "registro/alta_nodocente.html"
    form_class = NoDocenteForm
    success_url = reverse_lazy('registro_app:listar-nodocente')


class MateriaCreateView(CreateView):
    model = Materia
    template_name = "registro/alta_materia.html"
    form_class = MateriaForm
    success_url = reverse_lazy('registro_app:listar-materia')

class OficinaCreateView(CreateView):
    model = Oficina
    template_name = "registro/alta_oficina.html"
    form_class = OficinaForm
    success_url = reverse_lazy('registro_app:listar-oficina')
  
 

class DocenteUpdateView(UpdateView):
    model = Docente
    template_name = "registro/update_docente.html"
    form_class = DocenteForm
    success_url = reverse_lazy('registro_app:listar-docente')


class NoDocenteUpdateView(UpdateView):
    model = NoDocente
    template_name = "registro/update_nodocente.html"
    form_class = NoDocenteForm
    success_url = reverse_lazy('registro_app:listar-nodocente')


class MateriaUpdateView(UpdateView):
    model = Materia
    template_name = "registro/update_materia.html"
    form_class = MateriaForm
    success_url = reverse_lazy('registro_app:listar-materia')

class OficinaUpdateView(UpdateView):
    model = Oficina
    template_name = "registro/update_oficina.html"
    form_class = OficinaForm
    success_url = reverse_lazy('registro_app:listar-oficina')

class DocenteDeleteView(DeleteView):
    model = Docente
    template_name = "registro/delete_docente.html"
    success_url = reverse_lazy('registro_app:listar-docente')

class NoDocenteDeleteView(DeleteView):
    model = NoDocente
    template_name = "registro/delete_nodocente.html"
    success_url = reverse_lazy('registro_app:listar-nodocente')

class MateriaDeleteView(DeleteView):
    model = Materia
    template_name = "registro/delete_materia.html"
    success_url = reverse_lazy('registro_app:listar-materia')

class OficinaDeleteView(DeleteView):
    model = Oficina
    template_name = "registro/delete_oficina.html"
    success_url = reverse_lazy('registro_app:listar-oficina')


class VistaPrincipal(TemplateView):
    template_name = "index.html"

templates/registro/alta_docente.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row">
        <h1>Alta del Docente</h1>
    </div>
    <div class="row">
<form method="post" enctype="multipart/form-data">{% csrf_token %}{{form.as_p}}
    <button type="submit">Alta</button>
</form>

    </div>
</div>
    
{% endblock content %}

templates/registro/alta_materia.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row">
        <h1>Alta de la Materia</h1>
    </div>
    <div class="row">
<form method="post" enctype="multipart/form-data">{% csrf_token %}{{form.as_p}}
    <button type="submit">Alta</button>
</form>

    </div>
</div>
    
{% endblock content %}

templates/registro/alta_oficina.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h1>Alta de la Oficina</h1>
    </div>
    <div class="row">
<form method="post" enctype="multipart/form-data">{% csrf_token %}{{form.as_p}}
    <button type="submit">Alta</button>
</form>

    </div>
</div>  
{% endblock content %}

templates/registro/buscar_docente.html
<h1>Buscar por apellido:</h1>{% csrf_token %}
<form method ="GET">
   <input type ="text" name = 'kword' id = 'kword' placeholder="'Ingrese apellido">
   <button type="submit" class="btn btn-info">Buscar</button>
</form>

<h2>Resultados de la busqueda:</h2>
<ul>
    
    {% for docente in lista %}
    <li>{{ docente }}</li>
        
    {% endfor %}
        
</ul>

templates/registro/buscar_materia.html
<h1>Buscar materia:</h1>{% csrf_token %}
<form method ="GET">
   <input type ="text" name = 'kword' id = 'kword' placeholder="'Ingrese materia">
   <button type="submit" class="btn btn-info">Buscar</button>
</form>

<h2>Resultados de la busqueda:</h2>
<ul>
    
    {% for materia in lista %}
    <li>{{ materia }}</li>
        
    {% endfor %}
        
</ul>

templates/registro/buscar_nodocente.html
<h1>Buscar por apellido:</h1>{% csrf_token %}
<form method ="GET">
   <input type ="text" name = 'kword' id = 'kword' placeholder="Ingrese apellido">
   <button type="submit">Buscar</button>
</form>

<h2>Resultados de la busqueda:</h2>
<ul>
    
    {% for nodocente in lista %}
    <li>{{ nodocente }}</li>
        
    {% endfor %}
        
</ul>

templates/registro/delete_docente.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h2>Confirma la eliminacion?</h2>

    </div>
    <div class="row">
        <form method="post">{% csrf_token %}
            <button class="btn btn-danger" type="submit">OK</button>
        </form>

    </div>
</div>
    
{% endblock content %}
    

templates/registro/delete_materia.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h2>Confirma la eliminacion?</h2>

    </div>
    <div class="row">
        <form method="post">{% csrf_token %}
            <button class="btn btn-danger" type="submit">OK</button>
        </form>

    </div>
</div>   
{% endblock content %}

templates/registro/delete_oficina.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h2>Confirma la eliminacion?</h2>

    </div>
    <div class="row">
        <form method="post">{% csrf_token %}
            <button class="btn btn-danger" type="submit">OK</button>
        </form>

    </div>
</div>   
{% endblock content %}

templates/registro/detalle_docente.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h1>Detalle del Docente:</h1>
    </div>
    <div class="row">
        <div class="card" style="width:400px"> 
          {% if detalle_docente.avatar %}
          <img class="card-img-top" src="{{detalle_docente.avatar.url}}" alt="Card image" style="width:100%"> 
          {% else %}
          <img class="card-img-top" src="{% static 'img/avatar.jpeg'%}" alt="Card image" style="width:100%">
          {% endif %}
            
            <div class="card-body">
              <h4 class="card-title-center">{{detalle_docente.last_name}}, {{detalle_docente.first_name}}</h4>
              <p class="card-text-center">
                <ul>
                    <li>{{detalle_docente.age}} años</li>
                    <li>{{detalle_docente.materia}}</li>
                </ul>
              </p>
              <a href="{% url 'registro_app:update-docente' detalle_docente.id %}" class="btn btn-primary">Modificar</a>
            </div>
          </div>
    </div>
</div>    
{% endblock content %}

templates/registro/list_all_nodocente.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row justify-content-end mt-3">
    <form class="form-inline" method="GET"> {% csrf_token %}
      <input type="text" class="form-control mr-sm-2" placeholder="Inserte texto" id="kword" name="kword">
      <button type="submit" class="btn btn-primary mr-sm-2">Buscar</button>
      <a class="btn btn-info" href="{% url 'registro_app:alta-nodocente' %}">(+)Agregar</a>
    </form>

  </div>
  <div class="row">
    <h1>Lista de los No Docentes</h1>
    
  </div>
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Apellido</th>
          <th>Nombre</th>
          <th>Edad</th>
          <th>Oficina</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
          
          {% for nodocente in lista_nodocente  %}
          <tr>
              <td>{{ nodocente.last_name }}</td>
              <td>{{ nodocente.first_name }}</td>
              <td>{{ nodocente.age }}</td>
              <td>{{ nodocente.oficina }}</td>
              <td> 
                <a class="btn btn-info" href="{% url 'registro_app:detalle-nodocente' nodocente.id %}">Ver</a>
                <a class="btn btn-info" href="{% url 'registro_app:update-nodocente' nodocente.id %}">Modificar</a>
                <a class="btn btn-info" href="{% url 'registro_app:delete-nodocente' nodocente.id %}">Eliminar</a>
  
              </td>
          </tr>   
          {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row">
    {% if is_paginated %}
  <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Anterior</a></li>
          
      {% endif %}
      
      {% for pagina in paginator.page_range  %}
      
      {% ifequal pagina page_obj.number  %}
      <li class="page-item active"><a class="page-link" href="#">{{ pagina }}</a></li> 
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{ pagina }}</a></li> 
      {% endifequal %}    
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
      {% endif %}
  </ul>     
  {% endif %}
  </div>
</div>

  
{% endblock content %}

templates/registro/listar_por_materia.html
<h1>Lista de los docentes por materia:</h1>

<ul>
    
    {% for docente in lista %}
    <li>{{docente}}</li>
        
    {% endfor %}
        
</ul>

templates/registro/listar_por_oficina.html
<h1>Lista de los no docentes por oficina:</h1>

<ul>
    
    {% for nodocente in lista %}
    <li>{{ nodocente }}</li>
        
    {% endfor %}
        
</ul>

templates/registro/update_nodocente.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <h1>Modificar datos del No Docente</h1>
    </div>
    <div class="row">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}{{form.as_p}}
            <button type="submit">Modificar</button>
        </form>   
    </div>
</div>    
{% endblock content %}