applications/registro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='registro_app'

urlpatterns = [
    path('listar-docente/',views.DocenteListViewAll.as_view(), name='listar-docente'),
    path('listar-nodocente/',views.NoDocenteListViewAll.as_view(), name='listar-nodocente'),
    path('listar-por-materia/<short_name>/',views.DocenteListViewPorAsignatura.as_view(), name='listar-por-materia'),
    path('detalle-docente/<pk>/',views.DocenteDetailView.as_view(), name='detalle-docente'),
    path('detalle-nodocente/<pk>/',views.NoDocenteDetailView.as_view(), name='detalle-nodocente'),
    path('listar-por-oficina/<short_name>/',views.NoDocenteListViewPorOficina.as_view(), name='listar-por-oficina'),
    path('buscar-por-apellido/',views.DocenteListViewBuscar.as_view(), name='buscar-por-apellido'),
    path("buscar-nodocente-por-apellido/",views.NoDocenteListViewBuscar.as_view(), name="buscar-nodocente"),
    path("exito/",views.SuccessView.as_view(), name="exito"),
    path("alta-docente/",views.DocenteCreateView.as_view(), name="alta-docente"),
    path('alta-nodocente/',views.NoDocenteCreateView.as_view(), name='alta-nodocente'),
    path('update-docente/<pk>',views.DocenteUpdateView.as_view(), name='update-docente'),
    path('update-nodocente/<pk>', views.NoDocenteUpdateView.as_view(), name='update-nodocente'),
    path('delete-docente/<pk>', views.DocenteDeleteView.as_view(), name='delete-docente'),
    path('delete-nodocente/<pk>',views.NoDocenteDeleteView.as_view(), name='delete-nodocente'),
    path('listar-materia/', views.MateriaListViewAll.as_view(), name='listar-materia'),
    path('listar-oficina/', views.OficinaListViewAll.as_view(), name='listar-oficina'),
    path('', views.VistaPrincipal.as_view(), name='index'),
    path('detalle-materia/<pk>', views.MateriaDetailView.as_view(), name='detalle-materia'),
    path('buscar-materia/', views.MateriaListViewBuscar.as_view(), name='buscar-materia'),
    path('alta-materia/', views.MateriaCreateView.as_view(), name='alta-materia'),
    path('update-materia/<pk>', views.MateriaUpdateView.as_view(), name='update-materia'),
    path('delete-materia/<pk>', views.MateriaDeleteView.as_view(), name='delete-materia'),
    path('detalle-oficina/<pk>', views.OficinaDetailView.as_view(), name='detalle-oficina'),
    path('buscar-oficina/', views.OficinaListViewBuscar.as_view(), name='buscar-oficina'),
    path('alta-oficina/', views.OficinaCreateView.as_view(), name='alta-oficina'),
    path('update-oficina/<pk>', views.OficinaUpdateView.as_view(), name='update-oficina'),
    path('delete-oficina/<pk>', views.OficinaDeleteView.as_view(), name='delete-oficina'),
    
]

instituto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('applications.registro.urls')),
    ]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema CRUD</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <!-- Brand -->
            <a class="navbar-brand" href="#">CRUD</a>
          
            <!-- Toggler/collapsibe Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'registro_app:index' %}">Inicio</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown -toggle" href="" data-toggle="dropdown">Docentes</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'registro_app:listar-docente' %}">Listar Docentes</a>
                    <a class="dropdown-item" href="{% url 'registro_app:listar-materia' %}">Listar Materias</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown -toggle" href="{% url 'registro_app:listar-nodocente' %}" data-toggle="dropdown">No Docentes</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'registro_app:listar-nodocente' %}">Listar No Docentes</a>
                    <a class="dropdown-item" href="{% url 'registro_app:listar-oficina' %}">Listar Oficinas</a>
                  </div>
                </li>
              </ul>
            </div>
        </nav>
    
    
    {% block content %}
        
    {% endblock content %}
        
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="row text-center">
        <div class="col">
            <img class="img-fluid" src="{% static 'img/logo.png' %}" alt="Logo">
        </div>
    </div> 
{% endblock content %}
    